# Generated by Django 3.2.4 on 2021-08-05 19:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Um nome curto que será usado para identificar de forma única você na plataforma', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[w,@+-]+$'), 'Informe um nome de usuário válido Este valor deve conter apenas letras, númerose os caracteres: @/./+/-/_.', 'invalid')], verbose_name='Apelido / Usuário'),
        ),
    ]
