# Generated by Django 3.2.4 on 2021-08-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carrinho',
            unique_together={('chave_carrinho', 'produto')},
        ),
    ]
